resources:
  - ../../../bases/config
  - ../../../bases/httpbin
  - ../../../bases/openebs
  - ../../../bases/keycloak
  - ../../../bases/vault
  #- ../../../bases/zot
  - ../../../bases/immich


components:
  - ../../../components/replace-server-name