---
name: "Terraform Plan"

on:
  pull_request:
    
jobs:
  terraform:
    name: "Terraform Plan"    
    runs-on: gha-runner-scale-set
    container: hashicorp/terraform:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: my-step
        run: echo "Hello World! "
